/**
 * CLEANUP SCRIPT: Clear Old Junk Signals
 *
 * This script removes all signals generated by the old system before
 * the Institutional Signal Engine V2.0 was implemented.
 *
 * Run with: npx ts-node src/scripts/clearOldSignals.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function clearOldSignals() {
  console.log('🗑️  Starting cleanup of old signals...\n');

  try {
    // 1. Get count of signals to delete
    const signalCount = await prisma.signal.count();
    const accuracyCount = await prisma.signalAccuracy.count();

    console.log(`📊 Current database state:`);
    console.log(`   - Total signals: ${signalCount}`);
    console.log(`   - Total accuracy records: ${accuracyCount}\n`);

    if (signalCount === 0) {
      console.log('✅ Database already clean. No signals to delete.\n');
      return;
    }

    // 2. Ask for confirmation (in production, you might want to skip this)
    console.log('⚠️  WARNING: This will delete ALL signals and their accuracy records.');
    console.log('   This action cannot be undone.\n');

    // 3. Delete all SignalAccuracy records first (to avoid foreign key constraints)
    console.log('🗑️  Deleting signal accuracy records...');
    const deletedAccuracy = await prisma.signalAccuracy.deleteMany({});
    console.log(`   ✅ Deleted ${deletedAccuracy.count} accuracy records\n`);

    // 4. Delete all Signals
    console.log('🗑️  Deleting signals...');
    const deletedSignals = await prisma.signal.deleteMany({});
    console.log(`   ✅ Deleted ${deletedSignals.count} signals\n`);

    // 5. Verify cleanup
    const remainingSignals = await prisma.signal.count();
    const remainingAccuracy = await prisma.signalAccuracy.count();

    console.log('📊 Final database state:');
    console.log(`   - Remaining signals: ${remainingSignals}`);
    console.log(`   - Remaining accuracy records: ${remainingAccuracy}\n`);

    if (remainingSignals === 0 && remainingAccuracy === 0) {
      console.log('✅ Cleanup completed successfully!');
      console.log('🏦 The Institutional Signal Engine V2.0 will now generate fresh, high-quality signals.\n');
    } else {
      console.log('⚠️  Warning: Some records may not have been deleted. Please check manually.\n');
    }

  } catch (error) {
    console.error('❌ Error during cleanup:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run the cleanup
clearOldSignals()
  .then(() => {
    console.log('🎉 Script completed.');
    process.exit(0);
  })
  .catch((error) => {
    console.error('💥 Script failed:', error);
    process.exit(1);
  });
